[llm]
# OpenAI
api_key = "sk-proj-"
endpoint = "https://api.openai.com/v1"
#model = "gpt-4-turbo-preview"
model = "gpt-4o"

[vdb]
dbname = "memory"
user = "postgres"
password = "postgres"
hostaddr = "127.0.0.1"
port = "5432"

# Groq 
# rate_limit :/
#PI_KEY = ""
#ENDPOINT = "https://api.groq.com/openai/v1"
#MODEL = "llama3-70b-8192"

# Together
#API_KEY = ""
#ENDPOINT = "https://api.together.xyz/v1"
#MODEL = "meta-llama/Llama-3-70b-chat-hf"

# Fireworks
#API_KEY = ""
#ENDPOINT = "https://api.fireworks.ai/inference/v1"
#MODEL = "accounts/fireworks/models/llama-v3-70b-instruct"
